<footer>
    <!-- Contact Section -->
    <section class="contact-section bg-white py-0 pt-4">
    <div class="container">
        <div class="row mt-3">
        <div class="col-md-4 mb-3 mb-md-0">
            <div class="text-center">
            <i class="fas fa-envelope text-primary-darker mb-2"></i>
            <div class="small">
                <a href="mailto:info@manhattanmanor.com" class="text-black-75">info@manhattanmanor.com</a>
            </div>
            </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
            <div class="text-center">
            <i class="fas fa-mobile-alt text-primary-darker mb-2"></i>
            <div class="small">
                <a href="tel:212.489-9595" class="text-black-75">212.489-9595</a>
            </div>
            </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
            <div class="text-center">
            <i class="fas fa-map-marked-alt text-primary-darker mb-2"></i>
            <div class="small">
                <a href="#map" class="text-black-75 js-scroll-trigger">201 West 52nd Street, New York, NY</a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-12 text-black-75 text-center small mt-4">
        For Booking and Press Inquires please contact
        </div>

        <div class="col-12 text-black-75 text-center mt-0 mt-sm-3">
        <div class="row justify-content-around">

            <!-- 
            <div class="col-12 col-sm-6 mt-3 mt-sm-0 text-center">
            <span class="text-primary-darker small">Amanda Smith</span><br />
            <a href="mailto:amanda@manhattanmanor.com" class="small text-black-75">amanda@manhattanmanor.com</a><br />
            <a href="tel:646-358-2655" class="small text-black-75">646-358-2655</a><br />
            </div>
            <div class="col-12 col-sm-6 mt-3 mt-sm-0 text-center">
            <span class="text-primary-darker small">Mary Cawley</span><br />
            <a href="mailto:maryc@manhattanmanor.com" class="small text-black-75">maryc@manhattanmanor.com</a><br />
            <a href="tel:646-674-5805" class="small text-black-75">646-674-5805</a><br />
            </div>
            -->

            <div class="col-12 mt-3 mt-sm-0 text-center">
            <span class="text-primary-darker small">Amanda Smith</span><br />
            <a href="mailto:amanda@manhattanmanor.com" class="small text-black-75">amanda@manhattanmanor.com</a><br />
            <a href="tel:646-627-4329" class="small text-black-75">646-627-4329</a><br />
            </div>

        </div>
        </div>

        <div class="social d-flex flex-column align-items-center justify-content-center mt-4">
            <img alt="Manhattan Manor logo" src="/img/logo-big.png" style="max-width : 80px;" />

            <div class="languages mt-3">
                <a href="/index.php" aria-label="Go to Manhattan Manor english site">
                    <img alt="English" src="/img/usa.png" />
                </a>

                <a href="spa/index.php" aria-label="Go to Manhattan Manor spanish site">
                    <img alt="Español" src="/img/es.png" />
                </a>
            </div>
        </div>
        <div class="align-items-center" style="text-align: center; padding-top: 20px; padding-bottom: 20px">
            <span class="text-primary-darker small">Visit our sister restaurant</span><br><br>
                <a href="https://rosieogradys.com/" target="_blank"><img alt="Rosie O'Grady's Restaurant" src="/img/logo_rosie.png" /></a>
        </div>        

        <div class="row mt-4">
            <div class="col-md-4 order-md-1 mb-3 mb-md-0">
                <div class="text-center">
                <a href="./docs/MM-Specs.pdf" class="text-primary-darker" target="_blank">SKYLIGHT ROOM SPECS</a>
                </div>
            </div>

            <div class="col-md-4 order-md-3 mb-3 mb-md-0">
                <div class="text-center">
                <a href="./docs/MM-Specs.pdf" class="text-primary-darker" target="_blank">MANHATTAN CLUB SPECS</a>
                </div>
            </div>

            <div class="col-md-4 order-md-2 mb-3 mb-md-0">
                <div class="text-center">
                <!-- <a href="#" class="text-primary-darker" onclick="showModal('legalModal'); return false;">TERMS OF USE - PRIVACY POLICY</a> -->

                <a href="terms.php" class="text-primary-darker">TERMS OF USE - PRIVACY POLICY</a>
                </div>
            </div>
        </div>

        <div class="row mt-4 justify-content-center">
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="text-center">
                    <a href="accessibility.php" class="text-primary-darker" target="_blank">ACCESSIBILITY</a>
                </div>

                <div style="display: flex; flex-direction: row; justify-content: center; padding-top: 20px">
                    <a target="_blank" href="https://facebook.com/manhattanmanor" title="Facebook" style="">
                        <img src="/img/social/facebook_circle-30.png" alt="Facebook" title="Facebook" style="margin: 8px; opacity: 1;" width="40" height="40" border="0">
                    </a>
                    
                    <a target="_blank" href="https://www.instagram.com/manhattanmanor/" title="Instagram" style="">
                        <img src="/img/social/instagram-round-flat-30.png" alt="Instagram" title="Instagram" style="margin:8px;" width="40" height="40" border="0">
                    </a>
                    
                    <a class="" target="_blank" href="https://www.theknot.com/marketplace/manhattan-club-nyc-new-york-ny-2012844" title="TheKnot" style="">
                        <img src="/img/social/theknot-round.png" alt="TheKnot" title="TheKnot" style="margin:8px;" width="40" height="40" border="0">
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section class="small text-center text-black-75 py-4 bg-white">
        <div class="container">
            <div class="mb-3 mb-md-0">Copyright &copy; MANHATTAN MANOR 2021</div>

            <div class="small pt-4">
            All product names, logos, and brands are the property of their respective owners. All company, product and service names used in this website are for identification purposes only.
            </div>
            <div class="small pt-1">
            Use of these names, logos, and brands does not imply endorsement. 
            </div>
        </div>
    </section>
</footer>